# Generated by Django 2.2.1 on 2019-11-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('product_desc', models.TextField(verbose_name='产品描述')),
                ('product_use', models.CharField(max_length=32, verbose_name='产品用途')),
            ],
        ),
    ]
