# Generated by Django 2.2.1 on 2019-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191116_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='/images/1.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
