# Generated by Django 2.2.1 on 2019-11-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_time',
            field=models.DateField(auto_now=True, verbose_name='文章的时间'),
        ),
    ]
